spring:

  datasource:
    url: jdbc:postgresql://localhost:5439/product
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
  flyway:
    enabled: true
    locations: classpath:db/migrations
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: "0"


server:
  port: 8050
